var dac_sectors = [
  { code:'110' ,  parent:'0' ,  name:'EDUCATION' , description:``  },
  { code:'111' ,  parent:'110' ,  name:'Education, level unspecified' , description:`The codes in this category are to be used only when level of education is unspecified or unknown (e.g. training of primary school teachers should be coded under 11220).`  },
  { code:'11110' ,  parent:'111' ,  name:'Education policy and administrative management' , description:`Education sector policy, planning and programmes; aid to education ministries, administration and management systems; institution capacity building and advice; school management and governance; curriculum and materials development; unspecified education activities.`  },
  { code:'11120' ,  parent:'111' ,  name:'Education facilities and training' , description:`Educational buildings, equipment, materials; subsidiary services to education (boarding facilities, staff housing); language training; colloquia, seminars, lectures, etc.`  },
  { code:'11130' ,  parent:'111' ,  name:'Teacher training' , description:`Teacher education (where the level of education is unspecified); in-service and pre-service training; materials development.`  },
  { code:'11182' ,  parent:'111' ,  name:'Educational research' , description:`Research and studies on education effectiveness, relevance and quality; systematic evaluation and monitoring.`  },
  { code:'112' ,  parent:'110' ,  name:'Basic education' , description:``  },
  { code:'11220' ,  parent:'112' ,  name:'Primary education' , description:`Formal and non-formal primary education for children; all elementary and first cycle systematic instruction; provision of learning materials.`  },
  { code:'11230' ,  parent:'112' ,  name:'Basic life skills for youth and adults' , description:`Formal and non-formal education for basic life skills for young people and adults (adults education); literacy and numeracy training.`  },
  { code:'11231' ,  parent:'112' ,  name:'Basic life skills for youth' , description:`Formal and non-formal education for basic life skills for young people.`  },
  { code:'11232' ,  parent:'112' ,  name:'Primary education equivalent for adults' , description:`Formal primary education for adults.`  },
  { code:'11240' ,  parent:'112' ,  name:'Early childhood education' , description:`Formal and non-formal pre-school education.`  },
  { code:'113' ,  parent:'110' ,  name:'Secondary education' , description:``  },
  { code:'11320' ,  parent:'113' ,  name:'Secondary education' , description:`Second cycle systematic instruction at both junior and senior levels.`  },
  { code:'11321' ,  parent:'113' ,  name:'Lower secondary education' , description:`Second cycle systematic instruction at junior level.`  },
  { code:'11322' ,  parent:'113' ,  name:'Upper secondary education' , description:`Second cycle systematic instruction at senior level.`  },
  { code:'11330' ,  parent:'113' ,  name:'Vocational training' , description:`Elementary vocational training and secondary level technical education; on-the job training; apprenticeships; including informal vocational training.`  },
  { code:'114' ,  parent:'110' ,  name:'Post-secondary education' , description:``  },
  { code:'11420' ,  parent:'114' ,  name:'Higher education' , description:`Degree and diploma programmes at universities, colleges and polytechnics; scholarships.`  },
  { code:'11430' ,  parent:'114' ,  name:'Advanced technical and managerial training' , description:`Professional-level vocational training programmes and in-service training.`  },
  { code:'120' ,  parent:'0' ,  name:'HEALTH' , description:``  },
  { code:'121' ,  parent:'120' ,  name:'Health, general' , description:``  },
  { code:'12110' ,  parent:'121' ,  name:'Health policy and administrative management' , description:`Health sector policy, planning and programmes; aid to health ministries, public health administration; institution capacity building and advice; medical insurance programmes; unspecified health activities.`  },
  { code:'12181' ,  parent:'121' ,  name:'Medical education/training' , description:`Medical education and training for tertiary level services.`  },
  { code:'12182' ,  parent:'121' ,  name:'Medical research' , description:`General medical research (excluding basic health research).`  },
  { code:'12191' ,  parent:'121' ,  name:'Medical services' , description:`Laboratories, specialised clinics and hospitals (including equipment and supplies); ambulances; dental services; mental health care; medical rehabilitation; control of non-infectious diseases; drug and substance abuse control [excluding narcotics traffic control (16063)].`  },
  { code:'122' ,  parent:'120' ,  name:'Basic health' , description:``  },
  { code:'12220' ,  parent:'122' ,  name:'Basic health care' , description:`Basic and primary health care programmes; paramedical and nursing care programmes; supply of drugs, medicines and vaccines related to basic health care.`  },
  { code:'12230' ,  parent:'122' ,  name:'Basic health infrastructure' , description:`District-level hospitals, clinics and dispensaries and related medical equipment; excluding specialised hospitals and clinics (12191).`  },
  { code:'12240' ,  parent:'122' ,  name:'Basic nutrition' , description:`Direct feeding programmes (maternal feeding, breastfeeding and weaning foods, child feeding, school feeding); determination of micro-nutrient deficiencies; provision of vitamin A, iodine, iron etc.; monitoring of nutritional status; nutrition and food hygiene education; household food security.`  },
  { code:'12250' ,  parent:'122' ,  name:'Infectious disease control' , description:`Immunisation; prevention and control of infectious and parasite diseases, except malaria (12262), tuberculosis (12263), HIV/AIDS and other STDs (13040). It includes diarrheal diseases, vector-borne diseases (e.g. river blindness and guinea worm), viral diseases, mycosis, helminthiasis, zoonosis, diseases by other bacteria and viruses, pediculosis, etc.`  },
  { code:'12261' ,  parent:'122' ,  name:'Health education' , description:`Information, education and training of the population for improving health knowledge and practices; public health and awareness campaigns; promotion of improved personal hygiene practices, including use of sanitation facilities and handwashing with soap.`  },
  { code:'12262' ,  parent:'122' ,  name:'Malaria control' , description:`Prevention and control of malaria.`  },
  { code:'12263' ,  parent:'122' ,  name:'Tuberculosis control' , description:`Immunisation, prevention and control of tuberculosis.`  },
  { code:'12281' ,  parent:'122' ,  name:'Health personnel development' , description:`Training of health staff for basic health care services.`  },
  { code:'130' ,  parent:'0' ,  name:'POPULATION POLICIES/ PROGRAMMES AND REPRODUCTIVE HEALTH' , description:``  },
  { code:'13010' ,  parent:'130' ,  name:'Population policy and administrative management' , description:`Population/development policies; census work, vital registration; migration data; demographic research/analysis; reproductive health research; unspecified population activities.`  },
  { code:'13020' ,  parent:'130' ,  name:'Reproductive health care' , description:`Promotion of reproductive health; prenatal and postnatal care including delivery; prevention and treatment of infertility; prevention and management of consequences of abortion; safe motherhood activities.`  },
  { code:'13030' ,  parent:'130' ,  name:'Family planning' , description:`Family planning services including counselling; information, education and communication (IEC) activities; delivery of contraceptives; capacity building and training.`  },
  { code:'13040' ,  parent:'130' ,  name:'STD control including HIV/AIDS' , description:`All activities related to sexually transmitted diseases and HIV/AIDS control e.g. information, education and communication; testing; prevention; treatment, care.`  },
  { code:'13081' ,  parent:'130' ,  name:'Personnel development for population and reproductive health' , description:`Education and training of health staff for population and reproductive health care services.`  },
  { code:'140' ,  parent:'0' ,  name:'WATER AND SANITATION' , description:``  },
  { code:'14010' ,  parent:'140' ,  name:'Water sector policy and administrative management' , description:`Water sector policy and governance, including legislation, regulation, planning and management as well as transboundary management of water; institutional capacity development; activities supporting the Integrated Water Resource Management approach (IWRM: see box below).`  },
  { code:'14015' ,  parent:'140' ,  name:'Water resources conservation (including data collection)' , description:`Collection and usage of quantitative and qualitative data on water resources; creation and sharing of water knowledge; conservation and rehabilitation of inland surface waters (rivers, lakes etc.), ground water and coastal waters; prevention of water contamination.`  },
  { code:'14020' ,  parent:'140' ,  name:'Water supply and sanitation - large systems' , description:`Programmes where components according to 14021 and 14022 cannot be identified. When components are known, they should individually be reported under their respective purpose codes: water supply (14021), sanitation (14022), and hygiene (12261).`  },
  { code:'14021' ,  parent:'140' ,  name:'Water supply - large systems' , description:`Potable water treatment plants; intake works; storage; water supply pumping stations; large scale transmission / conveyance and distribution systems.`  },
  { code:'14022' ,  parent:'140' ,  name:'Sanitation - large systems' , description:`Large scale sewerage including trunk sewers and sewage pumping stations; domestic and industrial waste water treatment plants.`  },
  { code:'14030' ,  parent:'140' ,  name:'Basic drinking water supply and basic sanitation' , description:`Programmes where components according to 14031 and 14032 cannot be identified. When components are known, they should individually be reported under their respective purpose codes: water supply (14031), sanitation (14032), and hygiene (12261).`  },
  { code:'14031' ,  parent:'140' ,  name:'Basic drinking water supply' , description:`Rural water supply schemes using handpumps, spring catchments, gravity-fed systems, rainwater collection and fog harvesting, storage tanks, small distribution systems typically with shared connections/points of use. Urban schemes using handpumps and local neighbourhood networks including those with shared connections.`  },
  { code:'14032' ,  parent:'140' ,  name:'Basic sanitation' , description:`Latrines, on-site disposal and alternative sanitation systems, including the promotion of household and community investments in the construction of these facilities. (Use code 12261 for activities promoting improved personal hygiene practices.)`  },
  { code:'14040' ,  parent:'140' ,  name:'River basins’ development' , description:`Infrastructure-focused integrated river basin projects and related institutional activities; river flow control; dams and reservoirs [excluding dams primarily for irrigation (31140) and hydropower (23220) and activities related to river transport (21040)].`  },
  { code:'14050' ,  parent:'140' ,  name:'Waste management / disposal' , description:`Municipal and industrial solid waste management, including hazardous and toxic waste; collection, disposal and treatment; landfill areas; composting and reuse.`  },
  { code:'14081' ,  parent:'140' ,  name:'Education and training in water supply and sanitation' , description:`Education and training for sector professionals and service providers.`  },
  { code:'150' ,  parent:'0' ,  name:'GOVERNMENT AND CIVIL SOCIETY' , description:`Includes assistance to strengthen the administrative apparatus and government.`  },
  { code:'151' ,  parent:'150' ,  name:'Government and civil society, general' , description:`N.B. Use code 51010 for general budget support.`  },
  { code:'15110' ,  parent:'151' ,  name:'Public sector policy and administrative management' ,
   description:`Institution-building assistance to strengthen core public sector management systems and capacities.
   This includes macro-economic and other policy management, co-ordination, planning and reform; human resource management; organisational development; civil service reform; e-government; development planning, monitoring and evaluation; support to ministries involved in aid co-ordination; other ministries and government departments when sector cannot be specified. (Use specific sector codes for development of systems and capacities in sector ministries.)`
 },
  { code:'15121' ,  parent:'151' ,  name:'Foreign affairs' , description:`Administration of external affairs and services.`  },
  { code:'15122' ,  parent:'151' ,  name:'Diplomatic missions' , description:`Operation of diplomatic and consular missions stationed abroad or at offices of international organisations.`  },
  { code:'15123' ,  parent:'151' ,  name:'Administration of developing countries\' foreign aid' ,
  description:`Support to administration of developing countries' foreign aid (including triangular and south-south cooperation).`  },
  { code:'15124' ,  parent:'151' ,  name:'General personnel services' ,
  description:`Administration and operation of the civil service including policies, procedures and regulations.`  },
  { code:'15125' ,  parent:'151' ,  name:'Central procurement' ,
  description:`Administration and operation of centralised supply and purchasing services.`  },
  { code:'15126' ,  parent:'151' ,  name:'Other general public services' ,
  description:`Maintenance and storage of government records and archives, operation of government-owned or occupied buildings, central motor vehicle pools, government-operated printing offices, centralised computer and data processing services, etc.`  },
  { code:'15127' ,  parent:'151' ,  name:'National monitoring and evaluation' , description:`Operation or support of institutions providing national monitoring and evaluation.`  },
  { code:'15142' ,  parent:'151' ,  name:'Macroeconomic policy' , description:`Macroeconomic policy development and implementation.`  },
  { code:'15143' ,  parent:'151' ,  name:'Meteorological services' , description:`Operation or support of institutions dealing with weather forecasting.`  },
  { code:'15144' ,  parent:'151' ,  name:'National standards development' , description:`Operation or support of institutions dealing with national standards development. (Use code 16062 for statistical capacity-building.)`  },
  { code:'15154' ,  parent:'151' ,  name:'Executive office' , description:`Administration, operation or support of executive office. Includes office of the chief executive at all levels of government (monarch, governor-general, president, prime minister, governor, mayor, etc.).`  },
  { code:'15111' ,  parent:'151' ,  name:'Public Finance Management (PFM)' , description:`Fiscal policy and planning; support to ministries of finance; strengthening financial and managerial accountability; public expenditure management; improving financial management systems; budget drafting; inter-governmental fiscal relations, public audit, public debt. (Use code 15114 for domestic revenue mobilisation and code 33120 for customs).`  },
  { code:'15117' ,  parent:'151' ,  name:'Budget planning' , description:`Operation of the budget office and planning as part of the budget process.`  },
  { code:'15118' ,  parent:'151' ,  name:'National audit' , description:`Operation of the accounting and audit services.`  },
  { code:'15119' ,  parent:'151' ,  name:'Debt and aid management' , description:`Management of public debt and foreign aid received (in the partner country). For reporting on debt reorganisation, use codes 600xx.`  },
  { code:'15112' ,  parent:'151' ,  name:'Decentralisation and support to subnational government' , description:`Decentralisation processes (including political, administrative and fiscal dimensions); intergovernmental relations and federalism; strengthening departments of regional and local government, regional and local authorities and their national associations. (Use specific sector codes for decentralisation of sector management and services.)`  },
  { code:'15128' ,  parent:'151' ,  name:'Local government finance' , description:`Financial transfers to local government; support to institutions managing such transfers. (Use specific sector codes for sector-related transfers.)`  },
  { code:'15129' ,  parent:'151' ,  name:'Other central transfers to institutions' , description:`Transfers to non sector-specific autonomous bodies or state-owned enterprises outside of local government finance; support to institutions managing such transfers. (Use specific sector codes for sector-related transfers.)`  },
  { code:'15185' ,  parent:'151' ,  name:'Local government administration' , description:`Decentralisation processes (including political, administrative and fiscal dimensions); intergovernmental relations and federalism; strengthening local authorities.`  },
  { code:'15113' ,  parent:'151' ,  name:'Anti-corruption organisations and institutions' , description:`Specialised organisations, institutions and frameworks for the prevention of and combat against corruption, bribery, money- laundering and other aspects of organised crime, with or without law enforcement powers, e.g. anti-corruption commissions and monitoring bodies, special investigation services, institutions and initiatives of integrity and ethics oversight, specialised NGOs, other civil society and citizens’ organisations directly concerned with corruption.`  },
  { code:'15114' ,  parent:'151' ,  name:'Domestic Revenue Mobilisation' , description:`Support to domestic revenue mobilisation/tax policy, analysis and administration as well as non-tax public revenue, which includes work with ministries of finance, line ministries, revenue authorities or other local, regional or national public bodies. (Use code 16010 for social security and other social protection.)`  },
  { code:'15116' ,  parent:'151' ,  name:'Tax collection' , description:`Operation of the inland revenue authority.`  },
  { code:'15155' ,  parent:'151' ,  name:'Tax policy and administration support' , description:``  },
  { code:'15156' ,  parent:'151' ,  name:'Other non-tax revenue mobilisation' , description:`Non-tax public revenue, which includes line ministries, revenue authorities or other local, regional or national public bodies. `  },
  { code:'15130' ,  parent:'151' ,  name:'Legal and judicial development' ,
  description:`Support to institutions, systems and procedures of the justice sector, both formal and informal; support to ministries of justice, the interior and home affairs; judges and courts; legal drafting services; bar and lawyers associations; professional legal education; maintenance of law and order and public safety; border management; law enforcement agencies, police, prisons and their supervision; ombudsmen; alternative dispute resolution, arbitration and mediation; legal aid and counsel; traditional, indigenous and paralegal practices that fall outside the formal legal system. Measures that support the improvement of legal frameworks, constitutions, laws and regulations; legislative and constitutional drafting and review; legal reform; integration of formal and informal systems of law. Public legal education; dissemination of information on entitlements and remedies for injustice; awareness campaigns. (Use codes 152xx for activities that are primarily aimed at supporting security system reform or undertaken in connection with post-conflict and peace building activities.)`  },
  { code:'15131' ,  parent:'151' ,  name:'Justice, law and order policy, planning and administration' ,
  description:`Judicial law and order sectors; policy development within ministries of justice or equivalents.`  },
  { code:'15132' ,  parent:'151' ,  name:'Police' , description:`Police affairs and services.`  },
  { code:'15133' ,  parent:'151' ,  name:'Fire and rescue services' , description:`Fire-prevention and fire-fighting affairs and services.`  },
  { code:'15134' ,  parent:'151' ,  name:'Judicial affairs' , description:`Civil and criminal law courts and the judicial system, including enforcement of fines and legal settlements imposed by the courts and operation of parole and probation systems.`  },
  { code:'15135' ,  parent:'151' ,  name:'Ombudsman' , description:`Independent service representing the interests of the public by investigating and addressing complaints of unfair treatment or maladministration.`  },
  { code:'15136' ,  parent:'151' ,  name:'Immigration' , description:`Immigration affairs and services, including alien registration, issuing work and travel documents to immigrants.`  },
  { code:'15137' ,  parent:'151' ,  name:'Prisons' , description:``  },
  { code:'15150' ,  parent:'151' ,  name:'Democratic participation and civil society' , description:`Support to the exercise of democracy and diverse forms of participation of citizens beyond elections (15151); direct democracy instruments such as referenda and citizens’ initiatives; support to organisations to represent and advocate for their members, to monitor, engage and hold governments to account, and to help citizens learn to act in the public sphere; curricula and teaching for civic education at various levels. (This purpose code is restricted to activities targeting governance issues. When assistance to civil society is for non-governance purposes use other appropriate purpose codes.)`  },
  { code:'15151' ,  parent:'151' ,  name:'Elections' , description:`Electoral management bodies and processes, election observation, voters' education. (Use code 15230 when in the context of an international peacekeeping operation).`  },
  { code:'15152' ,  parent:'151' ,  name:'Legislatures and political parties' , description:`Assistance to strengthen key functions of legislatures/ parliaments including subnational assemblies and councils (representation; oversight; legislation), such as improving the capacity of legislative bodies, improving legislatures’ committees and administrative procedures,; research and information management systems; providing training programmes for legislators and support personnel. Assistance to political parties and strengthening of party systems.`  },
  { code:'15153' ,  parent:'151' ,  name:'Media and free flow of information' , description:`Activities that support free and uncensored flow of information on public issues; activities that increase the editorial and technical skills and the integrity of the print and broadcast media, e.g. training of journalists. (Use codes 22010-22040 for provision of equipment and capital assistance to media.)`  },
  { code:'15160' ,  parent:'151' ,  name:'Human rights' , description:`Measures to support specialised official human rights institutions and mechanisms at universal, regional, national and local levels in their statutory roles to promote and protect civil and political, economic, social and cultural rights as defined in international conventions and covenants; translation of international human rights commitments into national legislation; reporting and follow-up; human rights dialogue.
  Human rights defenders and human rights NGOs; human rights advocacy, activism, mobilisation; awareness raising and public human rights education.
  Human rights programming targeting specific groups, e.g. children, persons with disabilities, migrants, ethnic, religious, linguistic and sexual minorities, indigenous people and those suffering from caste discrimination, victims of trafficking, victims of torture.
  (Use code 15230 when in the context of a peacekeeping operation and code 15180 for ending violence against women and girls.)`  },
  { code:'15170' ,  parent:'151' ,  name:'Women’s equality organisations and institutions' , description:`Support for institutions and organisations (governmental and non-governmental) working for gender equality and women’s empowerment.`  },
  { code:'15180' ,  parent:'151' ,  name:'Ending violence against women and girls ' ,
  description:`Support to programmes designed to prevent and eliminate all forms of violence against women and girls/gender-based violence. This encompasses a broad range of forms of physical, sexual and psychological violence including but not limited to: intimate partner violence (domestic violence); sexual violence; female genital mutilation/cutting (FGM/C); child, early and forced marriage; acid throwing; honour killings; and trafficking of women and girls.
  Prevention activities may include efforts to empower women and girls; change attitudes, norms and behaviour; adopt and enact legal reforms; and strengthen implementation of laws and policies on ending violence against women and girls, including through strengthening institutional capacity.
  Interventions to respond to violence against women and girls/gender-based violence may include expanding access to services including legal assistance, psychosocial counselling and health care; training personnel to respond more effectively to the needs of survivors; and ensuring investigation, prosecution and punishment of perpetrators of violence.
  `  },
  { code:'152' ,  parent:'150' ,  name:'Conflict prevention and resolution, peace and security' , description:`N.B. Further notes on ODA eligibility (and exclusions) of conflict, peace and security related activities are given in paragraphs 76-81 of the Directives.`  },
  { code:'15210' ,  parent:'152' ,  name:'Security system management and reform' , description:`Technical co-operation provided to parliament, government ministries, law enforcement agencies and the judiciary to assist review and reform of the security system to improve democratic governance and civilian control; technical co-operation provided to government to improve civilian oversight and democratic control of budgeting, management, accountability and auditing of security expenditure, including military budgets, as part of a public expenditure management programme; assistance to civil society to enhance its competence and capacity to scrutinise the security system so that it is managed in accordance with democratic norms and principles of accountability, transparency and good governance. [Other than in the context of an international peacekeeping operation (15230).]`  },
  { code:'15220' ,  parent:'152' ,  name:'Civilian peace-building, conflict prevention and resolution' , description:`Support for civilian activities related to peace building, conflict prevention and resolution, including capacity building, monitoring, dialogue and information exchange. Bilateral participation in international civilian peace missions such as those conducted by the UN Department of Political Affairs (UNDPA) or the European Union (European Security and Defence Policy), and contributions to civilian peace funds or commissions (e.g. Peacebuilding Commission, Peacebuilding thematic window of the MDG achievement fund etc.). The contributions can take the form of financing or provision of equipment or civilian or military personnel (e.g. for training civilians). (Use code 15230 for bilateral participation in international peacekeeping operations).`  },
  { code:'15230' ,  parent:'152' ,  name:'Participation in international peacekeeping operations' ,
  description:`Bilateral participation in peacekeeping operations mandated or authorised by the United Nations (UN) through Security Council resolutions, and conducted by international organisations, e.g. UN, NATO, the European Union (Security and Defence Policy security-related operations), or regional groupings of developing countries.
  Direct contributions to the UN Department for Peacekeeping Operations (UNDPKO) budget are excluded from bilateral ODA
  (they are reportable in part as multilateral ODA, see Annex 9).
  The activities that can be reported as bilateral ODA under this code are limited to:
  human rights and election monitoring; reintegration of demobilised soldiers;
  rehabilitation of basic national infrastructure;
  monitoring or retraining of civil administrators and police forces;
  security sector reform and other rule of law-related activities;
  training in customs and border control procedures;
  advice or training in fiscal or macroeconomic stabilisation policy;
  repatriation and demobilisation of armed factions, and disposal of their weapons;
  explosive mine removal.
  The enforcement aspects of international peacekeeping operations are not reportable as ODA.
  ODA-eligible bilateral participation in peacekeeping operations can take the
  form of financing or provision of equipment or military or civilian personnel (e.g. police officers).
  The reportable cost is calculated as the excess over what the personnel and equipment would have cost to maintain had they not been assigned to take part in a peace operation. Costs for military contingents participating in UNDPKO peacekeeping operations are not reportable as ODA. International peacekeeping operations may include humanitarian-type activities (contributions to the form of equipment or personnel), as described in codes 7xxxx.
  These should be included under code 15230 if they are an integrated part of the activities above,
  otherwise they should be reported as humanitarian aid.
  NB: When using this code, indicate the name of the operation in the short description of the activity reported.`
  },
  { code:'15240' ,  parent:'152' ,  name:'Reintegration and SALW control' , description:`Reintegration of demobilised military personnel into the economy; conversion of production facilities from military to civilian outputs; technical co-operation to control, prevent and/or reduce the proliferation of small arms and light weapons (SALW) – see para. 80 of the Directives for definition of SALW activities covered. [Other than in the context of an international peacekeeping operation (15230) or child soldiers (15261)].`  },
  { code:'15250' ,  parent:'152' ,  name:'Removal of land mines and explosive remnants of war' , description:`All activities related to land mines and explosive remnants of war which have benefits to developing countries as their main objective, including removal of land mines and explosive remnants of war, and stockpile destruction for developmental purposes [other than in the context of an international peacekeeping operation (15230)]; risk education and awareness raising; rehabilitation, reintegration and assistance to victims, and research and development on demining and clearance. Only activities for civilian purposes are ODA-eligible.`  },
  { code:'15261' ,  parent:'152' ,  name:'Child soldiers (Prevention and demobilisation)' , description:`Technical co-operation provided to government – and assistance to civil society organisations – to support and apply legislation designed to prevent the recruitment of child soldiers, and to demobilise, disarm, reintegrate, repatriate and resettle (DDR) child soldiers.`  },
  { code:'160' ,  parent:'0' ,  name:'OTHER SOCIAL INFRASTRUCTURE AND SERVICES' , description:``  },
  { code:'16010' ,  parent:'160' ,  name:'Social/ welfare services' , description:`Social legislation and administration; institution capacity building and advice; social security and other social schemes; special programmes for the elderly, orphans, the disabled, street children; social dimensions of structural adjustment; unspecified social infrastructure and services, including consumer protection.`  },
  { code:'16011' ,  parent:'160' ,  name:'Social protection and welfare services policy, planning and administration' , description:`Administration of overall social protection policies, plans, programmes and budgets including legislation, standards and statistics on social protection.`  },
  { code:'16012' ,  parent:'160' ,  name:'Social security (excl pensions)' , description:`Social protection shemes in the form of cash or in-kind benefits to people unable to work due to sickness or injury.`  },
  { code:'16013' ,  parent:'160' ,  name:'General pensions' , description:`Social protection schemes in the form of cash or in-kind benefits, including pensions, against the risks linked to old age.`  },
  { code:'16014' ,  parent:'160' ,  name:'Civil service pensions' , description:`Pension schemes for government personnel.`  },
  { code:'16015' ,  parent:'160' ,  name:'Social services (incl youth development and women+ children)' , description:`Social protection schemes in the form of cash or in-kind benefits to households with dependent children, including parental leave benefits.`  },
  { code:'16020' ,  parent:'160' ,  name:'Employment policy and administrative management' , description:`Employment policy and planning; labour law; labour unions; institution capacity building and advice; support programmes for unemployed; employment creation and income generation programmes; occupational safety and health; combating child labour.`  },
  { code:'16030' ,  parent:'160' ,  name:'Housing policy and administrative management' , description:`Housing sector policy, planning and programmes; excluding low-cost housing and slum clearance (16040).`  },
  { code:'16040' ,  parent:'160' ,  name:'Low-cost housing' , description:`Including slum clearance.`  },
  { code:'16050' ,  parent:'160' ,  name:'Multisector aid for basic social services' , description:`Basic social services are defined to include basic education, basic health, basic nutrition, population/reproductive health and basic drinking water supply and basic sanitation.`  },
  { code:'16061' ,  parent:'160' ,  name:'Culture and recreation' , description:`Including libraries and museums.`  },
  { code:'16065' ,  parent:'160' ,  name:'Recreation and sport' , description:``  },
  { code:'16066' ,  parent:'160' ,  name:'Culture' , description:``  },
  { code:'16062' ,  parent:'160' ,  name:'Statistical capacity building' , description:`Both in national statistical offices and any other government ministries.`  },
  { code:'16063' ,  parent:'160' ,  name:'Narcotics control' , description:`In-country and customs controls including training of the police; educational programmes and awareness campaigns to restrict narcotics traffic and in-country distribution 1.`  },
  { code:'16064' ,  parent:'160' ,  name:'Social mitigation of HIV/AIDS' , description:`Special programmes to address the consequences of HIV/AIDS, e.g. social, legal and economic assistance to people living with HIV/AIDS including food security and employment; support to vulnerable groups and children orphaned by HIV/AIDS; human rights of HIV/AIDS affected people.`  },
  { code:'210' ,  parent:'0' ,  name:'TRANSPORT AND STORAGE' , description:`Note: Manufacturing of transport equipment should be included under code 32172.`  },
  { code:'21010' ,  parent:'210' ,  name:'Transport policy and administrative management' , description:`Transport sector policy, planning and programmes; aid to transport ministries; institution capacity building and advice; unspecified transport; activities that combine road, rail, water and/or air transport. Whenever possible, report transport of goods under the sector of the good being transported.`  },
  { code:'21011' ,  parent:'210' ,  name:'Transport policy, planning and administration' , description:`Administration of affairs and services concerning transport systems.`  },
  { code:'21012' ,  parent:'210' ,  name:'Public transport services' , description:`Administration of affairs and services concerning public transport.`  },
  { code:'21013' ,  parent:'210' ,  name:'Transport regulation' , description:`Supervision and regulation of users, operations, construction and maintenance of transport systems (registration, licensing, inspection of equipment, operator skills and training; safety standards, franchises, tarriffs, levels of service, etc.).`  },
  { code:'21020' ,  parent:'210' ,  name:'Road transport' , description:`Road infrastructure, road vehicles; passenger road transport, motor passenger cars.`  },
  { code:'21021' ,  parent:'210' ,  name:'Feeder road construction' , description:`Construction or operation of feeder road transport systems and facilities.`  },
  { code:'21022' ,  parent:'210' ,  name:'Feeder road maintenance' , description:`Maintenance of feeder road transport systems and facilities.`  },
  { code:'21023' ,  parent:'210' ,  name:'National road construction' , description:`Construction or operation of national road transport systems and facilities.`  },
  { code:'21024' ,  parent:'210' ,  name:'National road maintenance' , description:`Maintenance of national road transport systems and facilities.`  },
  { code:'21030' ,  parent:'210' ,  name:'Rail transport' , description:`Rail infrastructure, rail equipment, locomotives, other rolling stock; including light rail (tram) and underground systems.`  },
  { code:'21040' ,  parent:'210' ,  name:'Water transport' , description:`Harbours and docks, harbour guidance systems, ships and boats; river and other inland water transport, inland barges and vessels.`  },
  { code:'21050' ,  parent:'210' ,  name:'Air transport' , description:`Airports, airport guidance systems, aeroplanes, aeroplane maintenance equipment.`  },
  { code:'21061' ,  parent:'210' ,  name:'Storage' , description:`Whether or not related to transportation. Whenever possible, report storage projects under the sector of the resource being stored.`  },
  { code:'21081' ,  parent:'210' ,  name:'Education and training in transport and storage' , description:``  },
  { code:'220' ,  parent:'0' ,  name:'COMMUNICATIONS' , description:``  },
  { code:'22010' ,  parent:'220' ,  name:'Communications policy and administrative management' , description:`Communications sector policy, planning and programmes; institution capacity building and advice; including postal services development; unspecified communications activities.`  },
  { code:'22011' ,  parent:'220' ,  name:'Communications policy, planning and administration' , description:``  },
  { code:'22012' ,  parent:'220' ,  name:'Postal services' , description:`Development and operation of postal services.`  },
  { code:'22013' ,  parent:'220' ,  name:'Information services' , description:`Provision of information services.`  },
  { code:'22020' ,  parent:'220' ,  name:'Telecommunications' , description:`Telephone networks, telecommunication satellites, earth stations.`  },
  { code:'22030' ,  parent:'220' ,  name:'Radio/television/print media' , description:`Radio and TV links, equipment; newspapers; printing and publishing.`  },
  { code:'22040' ,  parent:'220' ,  name:'Information and communication technology (ICT)' , description:`Computer hardware and software; internet access; IT training. When sector cannot be specified.`  },
  { code:'230' ,  parent:'0' ,  name:'ENERGY GENERATION, DISTRIBUTION AND EFFICIENCY' , description:`Categories 231 through 235 include both electric power plants and combined heat and power (CHP) plants. Heat-only plants, whatever the type of fuel, are reportable under category 236. Activities relating to fuelwood/charcoal production, energy manufacturing and natural resources extraction (including oil and gas pipelines) are reportable under categories 312, 321 and 322 respectively.`  },
  { code:'231' ,  parent:'230' ,  name:'Energy generation, distribution and efficiency – general' , description:``  },
  { code:'23110' ,  parent:'231' ,  name:'Energy policy and administrative management' , description:`Energy sector policy, planning; aid to energy ministries; institution capacity building and advice; unspecified energy activities.`  },
  { code:'23111' ,  parent:'23110' ,  name:'Energy sector policy, planning and administration' , description:``  },
  { code:'23112' ,  parent:'23110' ,  name:'Energy regulation' , description:`Regulation of the energy sector, including wholesale and retail electricity provision.`  },
  { code:'23181' ,  parent:'23110' ,  name:'Energy education/training' , description:`All levels of training not included elsewhere.`  },
  { code:'23182' ,  parent:'23110' ,  name:'Energy research' , description:`Including general inventories, surveys.`  },
  { code:'23183' ,  parent:'23110' ,  name:'Energy conservation and demand-side efficiency' , description:`All projects in support of energy demand reduction, e.g. building and industry upgrades, smart grids, metering and tariffs. Also includes efficient cook-stoves and biogas projects.`  },
  { code:'232' ,  parent:'230' ,  name:'Energy generation, renewable sources' , description:``  },
  { code:'23210' ,  parent:'232' ,  name:'Energy generation, renewable sources – multiple technologies' , description:`Renewable energy generation programmes that cannot be attributed to one single technology (codes 23220 through 23280 below). Fuelwood/charcoal production should be included under forestry 31261.`  },
  { code:'23220' ,  parent:'232' ,  name:'Hydro-electric power plants' , description:`Including energy generating river barges.`  },
  { code:'23230' ,  parent:'232' ,  name:'Solar energy' , description:`Including photo-voltaic cells, solar thermal applications and solar heating.`  },
  { code:'23240' ,  parent:'232' ,  name:'Wind energy' , description:`Wind energy for water lifting and electric power generation.`  },
  { code:'23250' ,  parent:'232' ,  name:'Marine energy' , description:`Including ocean thermal energy conversion, tidal and wave power.`  },
  { code:'23260' ,  parent:'232' ,  name:'Geothermal energy' , description:`Use of geothermal energy for generating electric power or directly as heat for agriculture, etc.`  },
  { code:'23270' ,  parent:'232' ,  name:'Biofuel-fired power plants' , description:`Use of solids and liquids produced from biomass for direct power generation. Also includes biogases from anaerobic fermentation (e.g. landfill gas, sewage sludge gas, fermentation of energy crops and manure) and thermal processes (also known as syngas); waste-fired power plants making use of biodegradable municipal waste (household waste and waste from companies and public services that resembles household waste, collected at installations specifically designed for their disposal with recovery of combustible liquids, gases or heat). See code 23360 for non- renewable waste-fired power plants.`  },
  { code:'233' ,  parent:'230' ,  name:'Energy generation, non-renewable sources' , description:``  },
  { code:'23310' ,  parent:'233' ,  name:'Energy generation, non-renewable sources – unspecified' , description:`Thermal power plants including when energy source cannot be determined; combined gas-coal power plants.`  },
  { code:'23320' ,  parent:'233' ,  name:'Coal-fired electric power plants' , description:`Thermal electric power plants that use coal as the energy source.`  },
  { code:'23330' ,  parent:'233' ,  name:'Oil-fired electric power plants' , description:`Thermal electric power plants that use fuel oil or diesel fuel as the energy source.`  },
  { code:'23340' ,  parent:'233' ,  name:'Natural gas-fired electric power plants' , description:`Electric power plants that are fuelled by natural gas.`  },
  { code:'23350' ,  parent:'233' ,  name:'Fossil fuel electric power plants with carbon capture and storage (CCS)' , description:`Fossil fuel electric power plants employing technologies to capture carbon dioxide emissions. CCS not related to power plants should be included under 41020. CCS activities are not reportable as ODA.`  },
  { code:'23360' ,  parent:'233' ,  name:'Non-renewable waste-fired electric power plants' , description:`Electric power plants that use non-biodegradable industrial and municipal waste as the energy source.`  },
  { code:'234' ,  parent:'230' ,  name:'Hybrid energy electric power plants' , description:``  },
  { code:'23410' ,  parent:'234' ,  name:'Hybrid energy electric power plants' , description:`Electric power plants that make use of both non-renewable and renewable energy sources.`  },
  { code:'235' ,  parent:'230' ,  name:'Nuclear energy electric power plants' , description:``  },
  { code:'23510' ,  parent:'235' ,  name:'Nuclear energy electric power plants' , description:`Including nuclear safety.`  },
  { code:'236' ,  parent:'230' ,  name:'Heating, cooling and energy distribution' , description:``  },
  { code:'23610' ,  parent:'236' ,  name:'Heat plants' , description:`Power plants which are designed to produce heat only.`  },
  { code:'23620' ,  parent:'236' ,  name:'District heating and cooling' , description:`Distribution of heat generated in a centralised location, or delivery of chilled water, for residential and commercial heating or cooling purposes.`  },
  { code:'23630' ,  parent:'236' ,  name:'Electric power transmission and distribution' , description:`Grid distribution from power source to end user; transmission lines. Also includes storage of energy to generate power (e.g. pumped hydro, batteries) and the extension of grid access, often to rural areas.`  },
  { code:'23640' ,  parent:'236' ,  name:'Gas distribution' , description:`Delivery for use by ultimate consumer.`  },
  { code:'240' ,  parent:'0' ,  name:'BANKING AND FINANCIAL SERVICES' , description:``  },
  { code:'24010' ,  parent:'240' ,  name:'Financial policy and administrative management' , description:`Finance sector policy, planning and programmes; institution capacity building and advice; financial markets and systems.`  },
  { code:'24020' ,  parent:'240' ,  name:'Monetary institutions' , description:`Central banks.`  },
  { code:'24030' ,  parent:'240' ,  name:'Formal sector financial intermediaries' , description:`All formal sector financial intermediaries; credit lines; insurance, leasing, venture capital, etc. (except when focused on only one sector).`  },
  { code:'24040' ,  parent:'240' ,  name:'Informal/semi-formal financial intermediaries' , description:`Micro credit, savings and credit co-operatives etc.`  },
  { code:'24081' ,  parent:'240' ,  name:'Education/training in banking and financial services' , description:``  },
  { code:'250' ,  parent:'0' ,  name:'BUSINESS AND OTHER SERVICES' , description:``  },
  { code:'25010' ,  parent:'250' ,  name:'Business support services and institutions' , description:`Support to trade and business associations, chambers of commerce; legal and regulatory reform aimed at improving business and investment climate; private sector institution capacity building and advice; trade information; public-private sector networking including trade fairs; e-commerce. Where sector cannot be specified: general support to private sector enterprises (in particular, use code 32130 for enterprises in the industrial sector).`  },
  { code:'25020' ,  parent:'250' ,  name:'Privatisation' , description:`When sector cannot be specified. Including general state enterprise restructuring or demonopolisation programmes; planning, programming, advice.`  },
  { code:'311' ,  parent:'0' ,  name:'AGRICULTURE' , description:``  },
  { code:'31110' ,  parent:'311' ,  name:'Agricultural policy and administrative management' , description:`Agricultural sector policy, planning and programmes; aid to agricultural ministries; institution capacity building and advice; unspecified agriculture.`  },
  { code:'31120' ,  parent:'311' ,  name:'Agricultural development' , description:`Integrated projects; farm development.`  },
  { code:'31130' ,  parent:'311' ,  name:'Agricultural land resources' , description:`Including soil degradation control; soil improvement; drainage of water logged areas; soil desalination; agricultural land surveys; land reclamation; erosion control, desertification control.`  },
  { code:'31140' ,  parent:'311' ,  name:'Agricultural water resources' , description:`Irrigation, reservoirs, hydraulic structures, ground water exploitation for agricultural use.`  },
  { code:'31150' ,  parent:'311' ,  name:'Agricultural inputs' , description:`Supply of seeds, fertilizers, agricultural machinery/equipment.`  },
  { code:'31161' ,  parent:'311' ,  name:'Food crop production' , description:`Including grains (wheat, rice, barley, maize, rye, oats, millet, sorghum); horticulture; vegetables; fruit and berries; other annual and perennial crops. [Use code 32161 for agro-industries.]`  },
  { code:'31162' ,  parent:'311' ,  name:'Industrial crops/export crops' , description:`Including sugar; coffee, cocoa, tea; oil seeds, nuts, kernels; fibre crops; tobacco; rubber. [Use code 32161 for agro-industries.]`  },
  { code:'31163' ,  parent:'311' ,  name:'Livestock' , description:`Animal husbandry; animal feed aid.`  },
  { code:'31164' ,  parent:'311' ,  name:'Agrarian reform' , description:`Including agricultural sector adjustment.`  },
  { code:'31165' ,  parent:'311' ,  name:'Agricultural alternative development' , description:`Projects to reduce illicit drug cultivation through other agricultural marketing and production opportunities (see code 43050 for non-agricultural alternative development).`  },
  { code:'31166' ,  parent:'311' ,  name:'Agricultural extension' , description:`Non-formal training in agriculture.`  },
  { code:'31181' ,  parent:'311' ,  name:'Agricultural education/training' , description:``  },
  { code:'31182' ,  parent:'311' ,  name:'Agricultural research' , description:`Plant breeding, physiology, genetic resources, ecology, taxonomy, disease control, agricultural bio-technology; including livestock research (animal health, breeding and genetics, nutrition, physiology).`  },
  { code:'31191' ,  parent:'311' ,  name:'Agricultural services' , description:`Marketing policies & organisation; storage and transportation, creation of strategic reserves.`  },
  { code:'31192' ,  parent:'311' ,  name:'Plant and post-harvest protection and pest control' , description:`Including integrated plant protection, biological plant protection activities, supply and management of agrochemicals, supply of pesticides, plant protection policy and legislation.`  },
  { code:'31193' ,  parent:'311' ,  name:'Agricultural financial services' , description:`Financial intermediaries for the agricultural sector including credit schemes; crop insurance.`  },
  { code:'31194' ,  parent:'311' ,  name:'Agricultural co-operatives' , description:`Including farmers’ organisations.`  },
  { code:'31195' ,  parent:'311' ,  name:'Livestock/veterinary services' , description:`Animal health and management, genetic resources, feed resources.`  },
  { code:'312' ,  parent:'0' ,  name:'FORESTRY' , description:``  },
  { code:'31210' ,  parent:'312' ,  name:'Forestry policy and administrative management' , description:`Forestry sector policy, planning and programmes; institution capacity building and advice; forest surveys; unspecified forestry and agro-forestry activities.`  },
  { code:'31220' ,  parent:'312' ,  name:'Forestry development' , description:`Afforestation for industrial and rural consumption; exploitation and utilisation; erosion control, desertification control; integrated forestry projects.`  },
  { code:'31261' ,  parent:'312' ,  name:'Fuelwood/charcoal' , description:`Forestry development whose primary purpose is production of fuelwood and charcoal.`  },
  { code:'31281' ,  parent:'312' ,  name:'Forestry education/training' , description:``  },
  { code:'31282' ,  parent:'312' ,  name:'Forestry research' , description:`Including artificial regeneration, genetic improvement, production methods, fertilizer, harvesting.`  },
  { code:'31291' ,  parent:'312' ,  name:'Forestry services' , description:``  },
  { code:'313' ,  parent:'0' ,  name:'FISHING' , description:``  },
  { code:'31310' ,  parent:'313' ,  name:'Fishing policy and administrative management' , description:`Fishing sector policy, planning and programmes; institution capacity building and advice; ocean and coastal fishing; marine and freshwater fish surveys and prospecting; fishing boats/equipment; unspecified fishing activities.`  },
  { code:'31320' ,  parent:'313' ,  name:'Fishery development' , description:`Exploitation and utilisation of fisheries; fish stock protection; aquaculture; integrated fishery projects.`  },
  { code:'31381' ,  parent:'313' ,  name:'Fishery education/training' , description:``  },
  { code:'31382' ,  parent:'313' ,  name:'Fishery research' , description:`Pilot fish culture; marine/freshwater biological research.`  },
  { code:'31391' ,  parent:'313' ,  name:'Fishery services' , description:`Fishing harbours; fish markets; fishery transport and cold storage.`  },
  { code:'321' ,  parent:'0' ,  name:'INDUSTRY' , description:``  },
  { code:'32110' ,  parent:'321' ,  name:'Industrial policy and administrative management' , description:`Industrial sector policy, planning and programmes; institution capacity building and advice; unspecified industrial activities; manufacturing of goods not specified below.`  },
  { code:'32120' ,  parent:'321' ,  name:'Industrial development' , description:``  },
  { code:'32130' ,  parent:'321' ,  name:'Small and medium-sized enterprises (SME) development' , description:`Direct support to the development of small and medium-sized enterprises in the industrial sector, including accounting, auditing and advisory services.`  },
  { code:'32140' ,  parent:'321' ,  name:'Cottage industries and handicraft' , description:``  },
  { code:'32161' ,  parent:'321' ,  name:'Agro-industries' , description:`Staple food processing, dairy products, slaughter houses and equipment, meat and fish processing and preserving, oils/fats, sugar refineries, beverages/tobacco, animal feeds production.`  },
  { code:'32162' ,  parent:'321' ,  name:'Forest industries' , description:`Wood production, pulp/paper production.`  },
  { code:'32163' ,  parent:'321' ,  name:'Textiles, leather and substitutes' , description:`Including knitting factories.`  },
  { code:'32164' ,  parent:'321' ,  name:'Chemicals' , description:`Industrial and non-industrial production facilities; includes pesticides production.`  },
  { code:'32165' ,  parent:'321' ,  name:'Fertilizer plants' , description:``  },
  { code:'32166' ,  parent:'321' ,  name:'Cement/lime/plaster' , description:``  },
  { code:'32167' ,  parent:'321' ,  name:'Energy manufacturing' , description:`Including gas liquefaction; petroleum refineries.`  },
  { code:'32168' ,  parent:'321' ,  name:'Pharmaceutical production' , description:`Medical equipment/supplies; drugs, medicines, vaccines; hygienic products.`  },
  { code:'32169' ,  parent:'321' ,  name:'Basic metal industries' , description:`Iron and steel, structural metal production.`  },
  { code:'32170' ,  parent:'321' ,  name:'Non-ferrous metal industries' , description:``  },
  { code:'32171' ,  parent:'321' ,  name:'Engineering' , description:`Manufacturing of electrical and non-electrical machinery, engines/turbines.`  },
  { code:'32172' ,  parent:'321' ,  name:'Transport equipment industry' , description:`Shipbuilding, fishing boats building; railroad equipment; motor vehicles and motor passenger cars; aircraft; navigation/guidance systems.`  },
  { code:'32182' ,  parent:'321' ,  name:'Technological research and development' , description:`Including industrial standards; quality management; metrology; testing; accreditation; certification.`  },
  { code:'322' ,  parent:'0' ,  name:'MINERAL RESOURCES AND MINING' , description:``  },
  { code:'32210' ,  parent:'322' ,  name:'Mineral/mining policy and administrative management' , description:`Mineral and mining sector policy, planning and programmes; mining legislation, mining cadastre, mineral resources inventory, information systems, institution capacity building and advice; unspecified mineral resources exploitation.`  },
  { code:'32220' ,  parent:'322' ,  name:'Mineral prospection and exploration' , description:`Geology, geophysics, geochemistry; excluding hydrogeology (14010) and environmental geology (41010), mineral extraction and processing, infrastructure, technology, economics, safety and environment management.`  },
  { code:'32261' ,  parent:'322' ,  name:'Coal' , description:`Including lignite and peat.`  },
  { code:'32262' ,  parent:'322' ,  name:'Oil and gas' , description:`Petroleum, natural gas, condensates, liquefied petroleum gas (LPG), liquefied natural gas (LNG); including drilling and production, and oil and gas pipelines.`  },
  { code:'32263' ,  parent:'322' ,  name:'Ferrous metals' , description:`Iron and ferro-alloy metals.`  },
  { code:'32264' ,  parent:'322' ,  name:'Nonferrous metals' , description:`Aluminium, copper, lead, nickel, tin, zinc.`  },
  { code:'32265' ,  parent:'322' ,  name:'Precious metals/materials' , description:`Gold, silver, platinum, diamonds, gemstones.`  },
  { code:'32266' ,  parent:'322' ,  name:'Industrial minerals' , description:`Baryte, limestone, feldspar, kaolin, sand, gypsym, gravel, ornamental stones.`  },
  { code:'32267' ,  parent:'322' ,  name:'Fertilizer minerals' , description:`Phosphates, potash.`  },
  { code:'32268' ,  parent:'322' ,  name:'Offshore minerals' , description:`Polymetallic nodules, phosphorites, marine placer deposits.`  },
  { code:'323' ,  parent:'0' ,  name:'CONSTRUCTION' , description:``  },
  { code:'32310' ,  parent:'323' ,  name:'Construction policy and administrative management' , description:`Construction sector policy and planning; excluding construction activities within specific sectors (e.g., hospital or school construction).`  },
  { code:'331' ,  parent:'0' ,  name:'TRADE POLICY AND REGULATIONS AND TRADE- RELATED ADJUSTMENT' , description:``  },
  { code:'33110' ,  parent:'331' ,  name:'Trade policy and administrative Management' , description:`Trade policy and planning; support to ministries and departments responsible for trade policy; trade-related legislation and regulatory reforms; policy analysis and implementation of multilateral trade agreements e.g. technical barriers to trade and sanitary and phytosanitary measures (TBT/SPS) except at regional level (see 33130); mainstreaming trade in national development strategies (e.g. poverty reduction strategy papers); wholesale/retail trade; unspecified trade and trade promotion activities.`  },
  { code:'33120' ,  parent:'331' ,  name:'Trade facilitation' , description:`Simplification and harmonisation of international import and export procedures (e.g. customs valuation, licensing procedures, transport formalities, payments, insurance); support to customs departments  and other border agencies, including in particular implementation of the provisions of the WTO Trade Facilitation Agreement; tariff reforms.`  },
  { code:'33130' ,  parent:'331' ,  name:'Regional trade agreements (RTAs)' , description:`Support to regional trade arrangements [e.g. Southern African Development Community (SADC), Association of Southeast Asian Nations (ASEAN), Free Trade Area of the Americas (FTAA), African Caribbean Pacific/European Union (ACP/EU)], including work on technical barriers to trade and sanitary and phytosanitary measures (TBT/SPS) at regional level; elaboration of rules of origin and introduction of special and differential treatment in RTAs.`  },
  { code:'33140' ,  parent:'331' ,  name:'Multilateral trade negotiations' , description:`Support developing countries’ effective participation in multilateral trade negotiations, including training of negotiators, assessing impacts of negotiations; accession to the World Trade Organisation (WTO) and other multilateral trade-related organisations.`  },
  { code:'33150' ,  parent:'331' ,  name:'Trade-related adjustment' , description:`Contributions to the government budget to assist the implementation of recipients’ own trade reforms and adjustments to trade policy measures by other countries; assistance to manage shortfalls in the balance of payments due to changes in the world trading environment.`  },
  { code:'33181' ,  parent:'331' ,  name:'Trade education/training' , description:`Human resources development in trade not included under any of the above codes. Includes university programmes in trade.`  },
  { code:'332' ,  parent:'0' ,  name:'TOURISM' , description:``  },
  { code:'33210' ,  parent:'332' ,  name:'Tourism policy and administrative management' , description:``  },
  { code:'410' ,  parent:'0' ,  name:'General environmental protection' , description:`Covers activities concerned with conservation, protection or amelioration of the physical environment without sector allocation.`  },
  { code:'41010' ,  parent:'410' ,  name:'Environmental policy and administrative management' , description:`Environmental policy, laws, regulations and economic instruments; administrational institutions and practices; environmental and land use planning and decision-making procedures; seminars, meetings; miscellaneous conservation and protection measures not specified below.`  },
  { code:'41020' ,  parent:'410' ,  name:'Biosphere protection' , description:`Air pollution control, ozone layer preservation; marine pollution control.`  },
  { code:'41030' ,  parent:'410' ,  name:'Bio-diversity' , description:`Including natural reserves and actions in the surrounding areas; other measures to protect endangered or vulnerable species and their habitats (e.g. wetlands preservation).`  },
  { code:'41040' ,  parent:'410' ,  name:'Site preservation' , description:`Applies to unique cultural landscape; including sites/objects of historical, archeological, aesthetic, scientific or educational value.`  },
  { code:'41050' ,  parent:'410' ,  name:'Flood prevention/control' , description:`Floods from rivers or the sea; including sea water intrusion control and sea level rise related activities.`  },
  { code:'41081' ,  parent:'410' ,  name:'Environmental education/ training' , description:``  },
  { code:'41082' ,  parent:'410' ,  name:'Environmental research' , description:`Including establishment of databases, inventories/accounts of physical and natural resources; environmental profiles and impact studies if not sector specific.`  },
  { code:'430' ,  parent:'0' ,  name:'Other multisector' , description:``  },
  { code:'43010' ,  parent:'430' ,  name:'Multisector aid' , description:``  },
  { code:'43030' ,  parent:'430' ,  name:'Urban development and management' , description:`Integrated urban development projects; local development and urban management; urban infrastructure and services; municipal finances; urban environmental management; urban development and planning; urban renewal and urban housing; land information systems.`  },
  { code:'43031' ,  parent:'430' ,  name:'Urban land policy and management' , description:`Urban development and planning; urban management, land information systems.`  },
  { code:'43032' ,  parent:'430' ,  name:'Urban development' , description:`Integrated urban development projects; local development; urban infrastructure and services; municipal finances; urban environment systems; urban renewal and urban housing.`  },
  { code:'43040' ,  parent:'430' ,  name:'Rural development' , description:`Integrated rural development projects; e.g. regional development planning; promotion of decentralised and multi-sectoral competence for planning, co-ordination and management; implementation of regional development and measures (including natural reserve management); land management; land use planning; land settlement and resettlement activities [excluding resettlement of refugees and internally displaced persons (72010)]; functional integration of rural and urban areas; geographical information systems.`  },
  { code:'43041' ,  parent:'430' ,  name:'Rural land policy and management' , description:`Regional development planning; promotion of decentralised and multi-sectoral competence for planning, co-ordination and management; land management; land use planning; geographical information systems.`  },
  { code:'43042' ,  parent:'430' ,  name:'Rural development' , description:`Integrated rural development projects; implementation of regional development and measures (including natural reserve management); land settlement and resettlement activities [excluding resettlement of refugees and internally displaced persons (72010)]; functional integration of rural and urban areas.`  },
  { code:'43050' ,  parent:'430' ,  name:'Non-agricultural alternative development' , description:`Projects to reduce illicit drug cultivation through, for example, non-agricultural income opportunities, social and physical infrastructure (see code 31165 for agricultural alternative development).`  },
  { code:'43081' ,  parent:'430' ,  name:'Multisector education/training' , description:`Including scholarships.`  },
  { code:'43082' ,  parent:'430' ,  name:'Research/scientific institutions' , description:`When sector cannot be identified.`  },
  { code:'510' ,  parent:'0' ,  name:'General budget support' , description:`Budget support in the form of sector-wide approaches (SWAps) should be included in the respective sectors.`  },
  { code:'51010' ,  parent:'510' ,  name:'General budget support-related aid' , description:`Unearmarked contributions to the government budget; support for the implementation of macroeconomic reforms (structural adjustment programmes, poverty reduction strategies); general programme assistance (when not allocable by sector).`  },
  { code:'520' ,  parent:'0' ,  name:'Developmental food aid/Food security assistance' , description:``  },
  { code:'52010' ,  parent:'520' ,  name:'Food aid/Food security programmes' , description:`Supply of edible human food under national or international programmes including transport costs; cash payments made for food supplies; project food aid and food aid for market sales when benefiting sector not specified; excluding emergency food aid.
  Report as multilateral: i) food aid by the EU financed out of its budget and allocated pro rata to EU member countries; and ii) core contributions to the World Food Programme.`  },
  { code:'530' ,  parent:'0' ,  name:'Other commodity assistance' , description:`Non-food commodity assistance (when benefiting sector not specified).`  },
  { code:'53030' ,  parent:'530' ,  name:'Import support (capital goods)' , description:`Capital goods and services; lines of credit.`  },
  { code:'53040' ,  parent:'530' ,  name:'Import support (commodities)' , description:`Commodities, general goods and services, oil imports.`  },
  { code:'600' ,  parent:'0' ,  name:'Debt relief' , description:``  },
  { code:'60010' ,  parent:'600' ,  name:'Action relating to debt' , description:`Actions falling outside the code headings below.`  },
  { code:'60020' ,  parent:'600' ,  name:'Debt forgiveness' , description:``  },
  { code:'60030' ,  parent:'600' ,  name:'Relief of multilateral debt' , description:`Grants or credits to cover debt owed to multilateral financial institutions; including contributions to Heavily Indebted Poor Countries (HIPC) Trust Fund.`  },
  { code:'60040' ,  parent:'600' ,  name:'Rescheduling and refinancing' , description:``  },
  { code:'60061' ,  parent:'600' ,  name:'Debt for development swap' , description:`Allocation of debt claims to use for development (e.g., debt for education, debt for environment).`  },
  { code:'60062' ,  parent:'600' ,  name:'Other debt swap' , description:`Where the debt swap benefits an external agent i.e. is not specifically for development purposes.`  },
  { code:'60063' ,  parent:'600' ,  name:'Debt buy-back' , description:`Purchase of debt for the purpose of cancellation.`  },
  { code:'720' ,  parent:'0' ,  name:'Emergency Response' , description:`An emergency is a situation which results from man made crises and/or natural disasters.`  },
  { code:'72010' ,  parent:'720' ,  name:'Material relief assistance and services' , description:`Shelter, water, sanitation and health services, supply of medicines and other non-food relief items for the benefit of affected people and to facilitate the return to normal lives and livelihoods; assistance to refugees and internally displaced people in developing countries other than for food (72040) or protection (72050).`  },
  { code:'72040' ,  parent:'720' ,  name:'Emergency food aid' , description:`Food aid normally for general free distribution or special supplementary feeding programmes; short-term relief to targeted population groups affected by emergency situations. Excludes non-emergency food security assistance programmes/food aid (52010).`  },
  { code:'72050' ,  parent:'720' ,  name:'Relief co-ordination; protection and support services' , description:`Measures to co-ordinate delivery of humanitarian aid, including logistics and communications systems; measures to promote and protect the safety, well- being, dignity and integrity of civilians and those no longer taking part in hostilities. (Activities designed to protect the security of persons or property through the use or display of force are not reportable as ODA.)`  },
  { code:'730' ,  parent:'0' ,  name:'Reconstruction relief and rehabilitation' , description:`This relates to activities during and in the aftermath of an emergency situation. Longer-term activities to improve the level of infrastructure or social services should be reported under the relevant economic and social sector codes. See also guideline on distinguishing humanitarian from sector- allocable aid.`  },
  { code:'73010' ,  parent:'730' ,  name:'Reconstruction relief and rehabilitation' , description:`Short-term reconstruction work after emergency or conflict limited to restoring pre-existing infrastructure (e.g. repair or construction of roads, bridges and ports, restoration of essential facilities, such as water and sanitation, shelter, health care services); social and economic rehabilitation in the aftermath of emergencies to facilitate transition and enable populations to return to their previous livelihood or develop a new livelihood in the wake of an emergency situation (e.g. trauma counselling and treatment, employment programmes).`  },
  { code:'740' ,  parent:'0' ,  name:'Disaster prevention and preparedness' , description:`See codes 41050 and 15220 for prevention of floods and conflicts.`  },
  { code:'74010' ,  parent:'740' ,  name:'Disaster prevention and preparedness' , description:`Disaster risk reduction activities (e.g. developing knowledge, natural risks cartography, legal norms for construction); early warning systems; emergency contingency stocks and contingency planning including preparations for forced displacement.`  },
  { code:'910' ,  parent:'0' ,  name:'ADMINISTRATIVE COSTS OF DONORS' , description:``  },
  { code:'91010' ,  parent:'910' ,  name:'Administrative costs (non-sector allocable)' , description:``  },
  { code:'930' ,  parent:'0' ,  name:'REFUGEES IN DONOR COUNTRIES' , description:``  },
  { code:'93010' ,  parent:'930' ,  name:'Refugees in donor countries (non-sector allocable)' , description:``  },
  { code:'998' ,  parent:'0' ,  name:'UNALLOCATED/  UNSPECIFIED' , description:``  },
  { code:'99810' ,  parent:'998' ,  name:'Sectors not specified' , description:`Contributions to general development of the recipient should be included under programme assistance (51010).`  },
  { code:'99820' ,  parent:'998' ,  name:'Promotion of development awareness (non-sector allocable)' , description:`Spending in donor country for heightened awareness/interest in development co-operation (brochures, lectures, special research projects, etc.).`  },
]



var  sectors = new Map()

var root = { code: '0', name: 'root', children:[]}

sectors.set( 0 , root)

dac_sectors.forEach( (line) =>{
  line.children = []
  var parentCode
  var parent
    parentCode = parseInt(line.parent)
    if (sectors.has(parentCode)){
       sectors.set(parseInt(line.code), line)
       parent = sectors.get(parentCode)
       parent.children.push(line)
    }
} )


var fn = function(node){
  console.log( ` code ${node.code}  val ${node.name} parent ${node.parent}` )
  if (node.children){
   node.children.forEach( ch => fn(ch))
  }
}

//fn(root)

export default root
